apiVersion: v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: null
  generation: 1
  labels:
    app: webapp
  name: webapp
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: 172.30.78.46:5000/aveditor/webapp:latest
    generation: null
    importPolicy: {}
    name: latest
    referencePolicy:
      type: ""
